// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var master, searchByID;
    $('#list-head').hide();
    $('#details-head h3').hide();
    master = function(title) {
      return $.ajax({
        url: "http://www.omdbapi.com/?s=" + title
      }).done(function(data) {
        var movie, movieList, movies, _i, _len, _results;
        movies = $.parseJSON(data)['Search'];
        $('.tempList').remove();
        $('#details-head').hide();
        $('#list-head').show();
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          movieList = $("<div class=\"row\"> <div class=\"col-md-6\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.Title + " </span> </div> <div class=\"col-md-2\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.Year + " </span> </div> <div class=\"col-md-2\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.Type + " </span> </div> <div class=\"col-md-2\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.imdbID + "<span> </div> </div>");
          _results.push($(".movieAll").append(movieList));
        }
        return _results;
      });
    };
    searchByID = function(imdbID) {
      return $.ajax({
        url: "http://www.omdbapi.com/?i=" + imdbID + "&tomatoes=true&plot=full"
      }).done(function(data) {
        var movie, movieActors, movieAwards, movieCountry, movieDirector, movieGenre, movieImdbRating, movieLanguages, moviePlot, moviePoster, movieRuntime;
        movie = $.parseJSON(data);
        $('#details-head').find('h3').show();
        movieDirector = $("<span>" + movie.Director + "</span>");
        movieActors = $("<span>" + movie.Actors + "</span>");
        movieGenre = $("<span>" + movie.Genre + "</span>");
        movieRuntime = $("<span>" + movie.Runtime + "</span>");
        movieCountry = $("<span>" + movie.Country + "</span>");
        movieLanguages = $("<span>" + movie.Languages + "</span>");
        movieImdbRating = $("<span>" + movie.ImdbRating + "</span>");
        movieAwards = $("<span>" + movie.Awards + "</span>");
        moviePlot = $("<span>" + movie.Plot + "</span>");
        moviePoster = $("<span><img src=\"" + movie.Poster + "\"></span>");
        $('#details-head').show();
        $(".movie-director").html(movieDirector);
        $(".movie-actors").html(movieActors);
        $(".movie-genre").html(movieGenre);
        $(".movie-runtime").html(movieRuntime);
        $(".movie-country").html(movieCountry);
        $(".movie-languages").html(movieLanguages);
        $(".movie-imdbrating").html(movieImdbRating);
        $(".movie-awards").html(movieAwards);
        $(".movie-plot").html(moviePlot);
        return $(".movie-poster").html(moviePoster);
      });
    };
    $('#formSearch').on('submit', function(event) {
      var movieSearch;
      event.preventDefault();
      movieSearch = $('#titleContains').val();
      return master(movieSearch);
    });
    $('.movieAll').delegate('.row', 'mouseover', function(event) {
      return $(this).addClass('highlighted');
    });
    $('.movieAll').delegate('.row', 'mouseleave', function(event) {
      return $(this).removeClass('highlighted');
    });
    return $('.movieAll').delegate('.row', 'click', function(event) {
      var imdbID;
      imdbID = $(event.target).data('imdb');
      return searchByID(imdbID);
    });
  });

}).call(this);
