// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var master;
    master = function(title) {
      return $.ajax({
        url: "http://www.omdbapi.com/?s=" + title
      }).done(function(data) {
        var movie, movies, _i, _len, _results;
        movies = $.parseJSON(data)['Search'];
        $('.temp').remove();
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          _results.push($(".movieAll").append("<div class=\"temp\"> <div class=\"row\"> <div class=\"col-md-6\"> " + movie.Title + " </div> <div class=\"col-md-2\"> " + movie.Year + " </div> <div class=\"col-md-2\"> " + movie.Type + " </div> <div class=\"col-md-2\"> " + movie.imdbID + " </div> </div> </div>"));
        }
        return _results;
      });
    };
    return $('#formSearch').on('submit', function(event) {
      var movieSearch;
      event.preventDefault();
      movieSearch = $('#titleContains').val();
      return master(movieSearch);
    });
  });

}).call(this);
