// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var master;
    master = function(title) {
      return $.ajax({
        url: "http://www.omdbapi.com/?s=" + title
      }).done(function(data) {
        var movie, movies, _i, _len, _results;
        movies = $.parseJSON(data)['Search'];
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          _results.push($(".movieAll").replaceAll("<tr><td>" + movie.Title + "</td> <td>" + movie.Type + "</td> <td>" + movie.Year + "</td><td>" + movie.imdbID + "</td></tr>"));
        }
        return _results;
      });
    };
    return $('#form1').on('submit', function(event) {
      var movieSearch;
      event.preventDefault();
      movieSearch = $('#titleContains').val();
      return master(movieSearch);
    });
  });

}).call(this);
