// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var master, searchByID;
    master = function(title) {
      return $.ajax({
        url: "http://www.omdbapi.com/?s=" + title
      }).done(function(data) {
        var movie, movies, _i, _len, _results;
        movies = $.parseJSON(data)['Search'];
        $('.tempList').remove();
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          _results.push($(".movieAll").append("<div class=\"row\"> <div class=\"col-md-6\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.Title + "</span> </div> <div class=\"col-md-2\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.Year + "</span> </div> <div class=\"col-md-2\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.Type + "</span> </div> <div class=\"col-md-2\"> <span class=\"tempList\" data-imdb=" + movie.imdbID + "> " + movie.imdbID + "<span> </div> </div>"));
        }
        return _results;
      });
    };
    searchByID = function(imdbID) {
      return $.ajax({
        url: "http://www.omdbapi.com/?i=" + imdbID + "&tomatoes=true&plot=full"
      }).done(function(data) {
        var movie;
        movie = $.parseJSON(data);
        $('.tempPlot').remove();
        $(".moviePlot").append("<div class=\"tempPlot\">" + movie.Plot + "</div>");
        $('.tempPoster').remove();
        return $(".moviePoster").append("<div class=\"tempPoster\"> <img src=\"" + movie.Poster + "\"> </div>");
      });
    };
    $('#formSearch').on('submit', function(event) {
      var movieSearch;
      event.preventDefault();
      movieSearch = $('#titleContains').val();
      return master(movieSearch);
    });
    return $('body').delegate('span', 'click', function(event) {
      var imdbID;
      imdbID = $(event.target).data('imdb');
      return searchByID(imdbID);
    });
  });

}).call(this);
